# https://gist.github.com/danielwetan/4f4db933531db5dd1af2e69ec8d54d8a
name: publish

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/home/seba/los-ilustrados/neotaller/backend-dev/2023-uchile-dcc-bootcamp-losilustrados-project-backend
          git pull origin dev
          git checkout dev
          docker compose up -d --build
